// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_2DFilter (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_mat_data_V_dout,
        input_mat_data_V_empty_n,
        input_mat_data_V_read,
        output_mat_data_V_din,
        output_mat_data_V_full_n,
        output_mat_data_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_pp0_stage0 = 5'd4;
parameter    ap_ST_fsm_pp0_stage1 = 5'd8;
parameter    ap_ST_fsm_state7 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [6:0] input_mat_data_V_dout;
input   input_mat_data_V_empty_n;
output   input_mat_data_V_read;
output  [0:0] output_mat_data_V_din;
input   output_mat_data_V_full_n;
output   output_mat_data_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg input_mat_data_V_read;
reg output_mat_data_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    input_mat_data_V_blk_n;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] exitcond3_reg_882;
reg   [0:0] tmp_s_reg_870;
reg    output_mat_data_V_blk_n;
reg   [0:0] tmp_1_reg_874;
reg   [10:0] col_reg_358;
reg    ap_block_state1;
wire   [0:0] exitcond2_fu_369_p2;
wire    ap_CS_fsm_state2;
wire   [9:0] row_1_fu_375_p2;
reg   [9:0] row_1_reg_865;
wire   [0:0] tmp_s_fu_381_p2;
wire   [0:0] tmp_1_fu_387_p2;
wire   [0:0] tmp_4_fu_393_p2;
reg   [0:0] tmp_4_reg_878;
wire   [0:0] exitcond3_fu_426_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [10:0] col_1_fu_432_p2;
reg   [10:0] col_1_reg_886;
wire   [0:0] tmp_5_fu_438_p2;
reg   [0:0] tmp_5_reg_891;
wire   [0:0] tmp_6_fu_444_p2;
reg   [0:0] tmp_6_reg_895;
wire   [10:0] tmp_7_fu_450_p2;
reg   [10:0] tmp_7_reg_899;
wire   [0:0] tmp_8_i_fu_674_p2;
reg   [0:0] tmp_8_i_reg_919;
wire   [63:0] tmp_12_fu_731_p1;
reg   [63:0] tmp_12_reg_924;
reg   [63:0] tmp_12_reg_924_pp0_iter1_reg;
reg   [10:0] line_buffer_1_0_va_4_reg_935;
reg   [10:0] line_buffer_2_0_va_4_reg_941;
reg   [10:0] line_buffer_3_0_va_2_reg_947;
reg   [10:0] line_buffer_3_0_va_2_reg_947_pp0_iter1_reg;
wire   [10:0] line_buffer_4_0_va_6_gep_fu_304_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
reg    ap_predicate_op129_read_state4;
reg    ap_predicate_op146_write_state4;
reg    ap_block_state4_pp0_stage1_iter0;
wire    ap_block_state6_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_subdone;
reg   [10:0] line_buffer_0_0_va_address0;
reg    line_buffer_0_0_va_ce0;
reg    line_buffer_0_0_va_we0;
wire   [6:0] line_buffer_0_0_va_q0;
wire   [10:0] line_buffer_0_0_va_address1;
reg    line_buffer_0_0_va_ce1;
reg    line_buffer_0_0_va_we1;
reg   [10:0] line_buffer_1_0_va_address0;
reg    line_buffer_1_0_va_ce0;
reg    line_buffer_1_0_va_we0;
wire   [6:0] line_buffer_1_0_va_q0;
reg   [10:0] line_buffer_1_0_va_address1;
reg    line_buffer_1_0_va_ce1;
reg    line_buffer_1_0_va_we1;
wire   [6:0] line_buffer_1_0_va_q1;
reg   [10:0] line_buffer_2_0_va_address0;
reg    line_buffer_2_0_va_ce0;
reg    line_buffer_2_0_va_we0;
wire   [6:0] line_buffer_2_0_va_q0;
reg   [10:0] line_buffer_2_0_va_address1;
reg    line_buffer_2_0_va_ce1;
reg    line_buffer_2_0_va_we1;
wire   [6:0] line_buffer_2_0_va_q1;
reg   [10:0] line_buffer_3_0_va_address0;
reg    line_buffer_3_0_va_ce0;
reg    line_buffer_3_0_va_we0;
wire   [6:0] line_buffer_3_0_va_q0;
reg   [10:0] line_buffer_4_0_va_address0;
reg    line_buffer_4_0_va_ce0;
reg    line_buffer_4_0_va_we0;
wire   [6:0] line_buffer_4_0_va_q0;
reg   [10:0] line_buffer_4_0_va_address1;
reg    line_buffer_4_0_va_ce1;
reg    line_buffer_4_0_va_we1;
reg   [9:0] row_reg_347;
wire    ap_CS_fsm_state7;
reg   [10:0] ap_phi_mux_col_phi_fu_362_p4;
wire    ap_block_pp0_stage0;
wire   [63:0] tmp_10_fu_471_p1;
wire   [63:0] tmp_8_fu_738_p1;
reg    ap_block_pp0_stage1_11001;
reg    ap_block_pp0_stage1_01001;
reg   [7:0] IN_WINDOW_val_val_0_3_fu_86;
reg   [7:0] IN_WINDOW_val_val_0_2_fu_90;
reg   [7:0] IN_WINDOW_val_val_0_1_fu_94;
reg   [7:0] IN_WINDOW_val_0_val_fu_98;
wire   [7:0] IN_WINDOW_val_0_val_4_fu_742_p1;
reg   [7:0] IN_WINDOW_val_val_1_3_fu_102;
reg   [7:0] IN_WINDOW_val_val_1_2_fu_106;
reg   [7:0] IN_WINDOW_val_val_1_1_fu_110;
reg   [7:0] IN_WINDOW_val_1_val_fu_114;
wire   [7:0] IN_WINDOW_val_1_val_4_fu_746_p1;
reg   [7:0] IN_WINDOW_val_val_2_3_fu_118;
reg   [7:0] IN_WINDOW_val_val_2_2_fu_122;
reg   [7:0] IN_WINDOW_val_2_val_fu_126;
reg   [7:0] IN_WINDOW_val_2_val_1_fu_130;
wire   [7:0] IN_WINDOW_val_2_val_5_fu_750_p1;
wire   [10:0] tmp_9_fu_465_p2;
wire   [7:0] tmp_15_fu_490_p2;
wire   [7:0] tmp7_fu_520_p2;
wire   [7:0] tmp_14_fu_484_p2;
wire   [7:0] tmp_17_fu_502_p2;
wire   [7:0] tmp9_fu_532_p2;
wire   [7:0] tmp_13_fu_478_p2;
wire   [7:0] tmp8_fu_538_p2;
wire   [7:0] tmp6_fu_526_p2;
wire   [7:0] tmp_18_fu_508_p2;
wire   [7:0] tmp_16_fu_496_p2;
wire   [7:0] tmp_fu_550_p2;
wire   [7:0] tmp_19_fu_514_p2;
wire   [7:0] tmp2_fu_562_p2;
wire   [7:0] tmp3_fu_568_p2;
wire   [7:0] tmp1_fu_556_p2;
wire  signed [7:0] x_mag_2_2_2_i_fu_544_p2;
wire  signed [8:0] tmp_i_cast_fu_584_p1;
wire   [8:0] xs_V_3_fu_588_p2;
wire  signed [31:0] xs_V_1_i_i_i_cast_fu_594_p1;
wire   [0:0] p_Result_s_fu_608_p3;
reg   [31:0] p_Result_3_fu_598_p4;
wire  signed [31:0] p_Val2_1_fu_580_p1;
wire  signed [7:0] y_mag_2_2_2_i_fu_574_p2;
wire  signed [8:0] tmp_5_i_cast_fu_628_p1;
wire   [8:0] xs_V_4_fu_632_p2;
wire  signed [31:0] xs_V_1_i_i1_i_cast_fu_638_p1;
wire   [0:0] p_Result_2_fu_652_p3;
reg   [31:0] p_Result_4_fu_642_p4;
wire  signed [31:0] p_Val2_3_fu_624_p1;
wire   [31:0] agg_result_V_i_i_i_fu_616_p3;
wire   [31:0] agg_result_V_i_i4_i_fu_660_p3;
wire   [31:0] tmp_7_i_fu_668_p2;
wire   [10:0] tmp_11_fu_725_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_70;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

hls_2DFilter_linebkb #(
    .DataWidth( 7 ),
    .AddressRange( 1284 ),
    .AddressWidth( 11 ))
line_buffer_0_0_va_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_0_0_va_address0),
    .ce0(line_buffer_0_0_va_ce0),
    .we0(line_buffer_0_0_va_we0),
    .d0(line_buffer_1_0_va_q1),
    .q0(line_buffer_0_0_va_q0),
    .address1(line_buffer_0_0_va_address1),
    .ce1(line_buffer_0_0_va_ce1),
    .we1(line_buffer_0_0_va_we1),
    .d1(line_buffer_4_0_va_q0)
);

hls_2DFilter_linecud #(
    .DataWidth( 7 ),
    .AddressRange( 1284 ),
    .AddressWidth( 11 ))
line_buffer_1_0_va_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_1_0_va_address0),
    .ce0(line_buffer_1_0_va_ce0),
    .we0(line_buffer_1_0_va_we0),
    .d0(line_buffer_2_0_va_q1),
    .q0(line_buffer_1_0_va_q0),
    .address1(line_buffer_1_0_va_address1),
    .ce1(line_buffer_1_0_va_ce1),
    .we1(line_buffer_1_0_va_we1),
    .d1(line_buffer_4_0_va_q0),
    .q1(line_buffer_1_0_va_q1)
);

hls_2DFilter_linecud #(
    .DataWidth( 7 ),
    .AddressRange( 1284 ),
    .AddressWidth( 11 ))
line_buffer_2_0_va_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_2_0_va_address0),
    .ce0(line_buffer_2_0_va_ce0),
    .we0(line_buffer_2_0_va_we0),
    .d0(line_buffer_3_0_va_q0),
    .q0(line_buffer_2_0_va_q0),
    .address1(line_buffer_2_0_va_address1),
    .ce1(line_buffer_2_0_va_ce1),
    .we1(line_buffer_2_0_va_we1),
    .d1(line_buffer_4_0_va_q0),
    .q1(line_buffer_2_0_va_q1)
);

hls_2DFilter_lineeOg #(
    .DataWidth( 7 ),
    .AddressRange( 1284 ),
    .AddressWidth( 11 ))
line_buffer_3_0_va_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_3_0_va_address0),
    .ce0(line_buffer_3_0_va_ce0),
    .we0(line_buffer_3_0_va_we0),
    .d0(line_buffer_4_0_va_q0),
    .q0(line_buffer_3_0_va_q0)
);

hls_2DFilter_linebkb #(
    .DataWidth( 7 ),
    .AddressRange( 1284 ),
    .AddressWidth( 11 ))
line_buffer_4_0_va_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_4_0_va_address0),
    .ce0(line_buffer_4_0_va_ce0),
    .we0(line_buffer_4_0_va_we0),
    .d0(input_mat_data_V_dout),
    .q0(line_buffer_4_0_va_q0),
    .address1(line_buffer_4_0_va_address1),
    .ce1(line_buffer_4_0_va_ce1),
    .we1(line_buffer_4_0_va_we1),
    .d1(input_mat_data_V_dout)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond2_fu_369_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond2_fu_369_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((exitcond2_fu_369_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_reg_882 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        col_reg_358 <= col_1_reg_886;
    end else if (((exitcond2_fu_369_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        col_reg_358 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        row_reg_347 <= 10'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        row_reg_347 <= row_1_reg_865;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_874 == 1'd1) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        IN_WINDOW_val_0_val_fu_98[6 : 0] <= IN_WINDOW_val_0_val_4_fu_742_p1[6 : 0];
        IN_WINDOW_val_1_val_fu_114[6 : 0] <= IN_WINDOW_val_1_val_4_fu_746_p1[6 : 0];
        IN_WINDOW_val_2_val_1_fu_130[6 : 0] <= IN_WINDOW_val_2_val_5_fu_750_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_874 == 1'd1) & (exitcond3_fu_426_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        IN_WINDOW_val_2_val_fu_126[6 : 0] <= IN_WINDOW_val_2_val_1_fu_130[6 : 0];
        IN_WINDOW_val_val_0_1_fu_94[6 : 0] <= IN_WINDOW_val_0_val_fu_98[6 : 0];
        IN_WINDOW_val_val_0_2_fu_90[6 : 0] <= IN_WINDOW_val_val_0_1_fu_94[6 : 0];
        IN_WINDOW_val_val_0_3_fu_86[6 : 0] <= IN_WINDOW_val_val_0_2_fu_90[6 : 0];
        IN_WINDOW_val_val_1_1_fu_110[6 : 0] <= IN_WINDOW_val_1_val_fu_114[6 : 0];
        IN_WINDOW_val_val_1_2_fu_106[6 : 0] <= IN_WINDOW_val_val_1_1_fu_110[6 : 0];
        IN_WINDOW_val_val_1_3_fu_102[6 : 0] <= IN_WINDOW_val_val_1_2_fu_106[6 : 0];
        IN_WINDOW_val_val_2_2_fu_122[6 : 0] <= IN_WINDOW_val_2_val_fu_126[6 : 0];
        IN_WINDOW_val_val_2_3_fu_118[6 : 0] <= IN_WINDOW_val_val_2_2_fu_122[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        col_1_reg_886 <= col_1_fu_432_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond3_reg_882 <= exitcond3_fu_426_p2;
        line_buffer_3_0_va_2_reg_947_pp0_iter1_reg <= line_buffer_3_0_va_2_reg_947;
        tmp_12_reg_924_pp0_iter1_reg[10 : 0] <= tmp_12_reg_924[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_426_p2 == 1'd0) & (tmp_4_reg_878 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buffer_1_0_va_4_reg_935 <= tmp_12_fu_731_p1;
        line_buffer_2_0_va_4_reg_941 <= tmp_12_fu_731_p1;
        line_buffer_3_0_va_2_reg_947 <= tmp_12_fu_731_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        row_1_reg_865 <= row_1_fu_375_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_426_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_12_reg_924[10 : 0] <= tmp_12_fu_731_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_369_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_1_reg_874 <= tmp_1_fu_387_p2;
        tmp_4_reg_878 <= tmp_4_fu_393_p2;
        tmp_s_reg_870 <= tmp_s_fu_381_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_870 == 1'd1) & (exitcond3_fu_426_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_5_reg_891 <= tmp_5_fu_438_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_870 == 1'd1) & (tmp_5_fu_438_p2 == 1'd0) & (exitcond3_fu_426_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_6_reg_895 <= tmp_6_fu_444_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_870 == 1'd1) & (tmp_6_fu_444_p2 == 1'd0) & (tmp_5_fu_438_p2 == 1'd0) & (exitcond3_fu_426_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_7_reg_899 <= tmp_7_fu_450_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_874 == 1'd1) & (exitcond3_fu_426_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_8_i_reg_919 <= tmp_8_i_fu_674_p2;
    end
end

always @ (*) begin
    if ((exitcond3_fu_426_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond2_fu_369_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_col_phi_fu_362_p4 = col_1_reg_886;
    end else begin
        ap_phi_mux_col_phi_fu_362_p4 = col_reg_358;
    end
end

always @ (*) begin
    if (((tmp_s_reg_870 == 1'd1) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_mat_data_V_blk_n = input_mat_data_V_empty_n;
    end else begin
        input_mat_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_predicate_op129_read_state4 == 1'b1))) begin
        input_mat_data_V_read = 1'b1;
    end else begin
        input_mat_data_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond2_fu_369_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            line_buffer_0_0_va_address0 = tmp_12_reg_924;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            line_buffer_0_0_va_address0 = tmp_10_fu_471_p1;
        end else begin
            line_buffer_0_0_va_address0 = 'bx;
        end
    end else begin
        line_buffer_0_0_va_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        line_buffer_0_0_va_ce0 = 1'b1;
    end else begin
        line_buffer_0_0_va_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_0_0_va_ce1 = 1'b1;
    end else begin
        line_buffer_0_0_va_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_4_reg_878 == 1'd0) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buffer_0_0_va_we0 = 1'b1;
    end else begin
        line_buffer_0_0_va_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_4_reg_878 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_0_0_va_we1 = 1'b1;
    end else begin
        line_buffer_0_0_va_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            line_buffer_1_0_va_address0 = line_buffer_1_0_va_4_reg_935;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            line_buffer_1_0_va_address0 = tmp_10_fu_471_p1;
        end else begin
            line_buffer_1_0_va_address0 = 'bx;
        end
    end else begin
        line_buffer_1_0_va_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_1_0_va_address1 = tmp_12_reg_924_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_0_va_address1 = tmp_12_fu_731_p1;
    end else begin
        line_buffer_1_0_va_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        line_buffer_1_0_va_ce0 = 1'b1;
    end else begin
        line_buffer_1_0_va_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        line_buffer_1_0_va_ce1 = 1'b1;
    end else begin
        line_buffer_1_0_va_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_4_reg_878 == 1'd0) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buffer_1_0_va_we0 = 1'b1;
    end else begin
        line_buffer_1_0_va_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_4_reg_878 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_1_0_va_we1 = 1'b1;
    end else begin
        line_buffer_1_0_va_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            line_buffer_2_0_va_address0 = line_buffer_2_0_va_4_reg_941;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            line_buffer_2_0_va_address0 = tmp_10_fu_471_p1;
        end else begin
            line_buffer_2_0_va_address0 = 'bx;
        end
    end else begin
        line_buffer_2_0_va_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_2_0_va_address1 = tmp_12_reg_924_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_2_0_va_address1 = tmp_12_fu_731_p1;
    end else begin
        line_buffer_2_0_va_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        line_buffer_2_0_va_ce0 = 1'b1;
    end else begin
        line_buffer_2_0_va_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        line_buffer_2_0_va_ce1 = 1'b1;
    end else begin
        line_buffer_2_0_va_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_4_reg_878 == 1'd0) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buffer_2_0_va_we0 = 1'b1;
    end else begin
        line_buffer_2_0_va_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_4_reg_878 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_2_0_va_we1 = 1'b1;
    end else begin
        line_buffer_2_0_va_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_4_reg_878 == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_3_0_va_address0 = tmp_12_reg_924_pp0_iter1_reg;
    end else if (((tmp_4_reg_878 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        line_buffer_3_0_va_address0 = line_buffer_3_0_va_2_reg_947_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_3_0_va_address0 = tmp_12_fu_731_p1;
    end else begin
        line_buffer_3_0_va_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_4_reg_878 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((tmp_4_reg_878 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        line_buffer_3_0_va_ce0 = 1'b1;
    end else begin
        line_buffer_3_0_va_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_reg_878 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((tmp_4_reg_878 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        line_buffer_3_0_va_we0 = 1'b1;
    end else begin
        line_buffer_3_0_va_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_4_reg_878 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_4_0_va_address0 = line_buffer_4_0_va_6_gep_fu_304_p3;
    end else if (((tmp_4_reg_878 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_4_0_va_address0 = tmp_12_reg_924;
    end else if (((tmp_5_reg_891 == 1'd1) & (tmp_s_reg_870 == 1'd1) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buffer_4_0_va_address0 = 64'd0;
    end else if (((tmp_6_reg_895 == 1'd1) & (tmp_s_reg_870 == 1'd1) & (tmp_5_reg_891 == 1'd0) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buffer_4_0_va_address0 = 64'd1280;
    end else if (((tmp_s_reg_870 == 1'd1) & (tmp_6_reg_895 == 1'd0) & (tmp_5_reg_891 == 1'd0) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buffer_4_0_va_address0 = tmp_8_fu_738_p1;
    end else begin
        line_buffer_4_0_va_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_70)) begin
        if ((tmp_5_reg_891 == 1'd1)) begin
            line_buffer_4_0_va_address1 = 64'd1;
        end else if (((tmp_6_reg_895 == 1'd1) & (tmp_5_reg_891 == 1'd0))) begin
            line_buffer_4_0_va_address1 = 64'd1279;
        end else begin
            line_buffer_4_0_va_address1 = 'bx;
        end
    end else begin
        line_buffer_4_0_va_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_5_reg_891 == 1'd1) & (tmp_s_reg_870 == 1'd1) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((tmp_6_reg_895 == 1'd1) & (tmp_s_reg_870 == 1'd1) & (tmp_5_reg_891 == 1'd0) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((tmp_s_reg_870 == 1'd1) & (tmp_6_reg_895 == 1'd0) & (tmp_5_reg_891 == 1'd0) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((tmp_4_reg_878 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_4_reg_878 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        line_buffer_4_0_va_ce0 = 1'b1;
    end else begin
        line_buffer_4_0_va_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_5_reg_891 == 1'd1) & (tmp_s_reg_870 == 1'd1) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((tmp_6_reg_895 == 1'd1) & (tmp_s_reg_870 == 1'd1) & (tmp_5_reg_891 == 1'd0) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        line_buffer_4_0_va_ce1 = 1'b1;
    end else begin
        line_buffer_4_0_va_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_5_reg_891 == 1'd1) & (tmp_s_reg_870 == 1'd1) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((tmp_6_reg_895 == 1'd1) & (tmp_s_reg_870 == 1'd1) & (tmp_5_reg_891 == 1'd0) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((tmp_s_reg_870 == 1'd1) & (tmp_6_reg_895 == 1'd0) & (tmp_5_reg_891 == 1'd0) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        line_buffer_4_0_va_we0 = 1'b1;
    end else begin
        line_buffer_4_0_va_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_5_reg_891 == 1'd1) & (tmp_s_reg_870 == 1'd1) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((tmp_6_reg_895 == 1'd1) & (tmp_s_reg_870 == 1'd1) & (tmp_5_reg_891 == 1'd0) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        line_buffer_4_0_va_we1 = 1'b1;
    end else begin
        line_buffer_4_0_va_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_reg_874 == 1'd1) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        output_mat_data_V_blk_n = output_mat_data_V_full_n;
    end else begin
        output_mat_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_predicate_op146_write_state4 == 1'b1))) begin
        output_mat_data_V_write = 1'b1;
    end else begin
        output_mat_data_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond2_fu_369_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond3_fu_426_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((exitcond3_fu_426_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign IN_WINDOW_val_0_val_4_fu_742_p1 = line_buffer_0_0_va_q0;

assign IN_WINDOW_val_1_val_4_fu_746_p1 = line_buffer_1_0_va_q0;

assign IN_WINDOW_val_2_val_5_fu_750_p1 = line_buffer_2_0_va_q0;

assign agg_result_V_i_i4_i_fu_660_p3 = ((p_Result_2_fu_652_p3[0:0] === 1'b1) ? p_Result_4_fu_642_p4 : p_Val2_3_fu_624_p1);

assign agg_result_V_i_i_i_fu_616_p3 = ((p_Result_s_fu_608_p3[0:0] === 1'b1) ? p_Result_3_fu_598_p4 : p_Val2_1_fu_580_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((output_mat_data_V_full_n == 1'b0) & (ap_predicate_op146_write_state4 == 1'b1)) | ((input_mat_data_V_empty_n == 1'b0) & (ap_predicate_op129_read_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((output_mat_data_V_full_n == 1'b0) & (ap_predicate_op146_write_state4 == 1'b1)) | ((input_mat_data_V_empty_n == 1'b0) & (ap_predicate_op129_read_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((output_mat_data_V_full_n == 1'b0) & (ap_predicate_op146_write_state4 == 1'b1)) | ((input_mat_data_V_empty_n == 1'b0) & (ap_predicate_op129_read_state4 == 1'b1))));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage1_iter0 = (((output_mat_data_V_full_n == 1'b0) & (ap_predicate_op146_write_state4 == 1'b1)) | ((input_mat_data_V_empty_n == 1'b0) & (ap_predicate_op129_read_state4 == 1'b1)));
end

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_70 = ((tmp_s_reg_870 == 1'd1) & (exitcond3_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op129_read_state4 = ((tmp_s_reg_870 == 1'd1) & (exitcond3_reg_882 == 1'd0));
end

always @ (*) begin
    ap_predicate_op146_write_state4 = ((tmp_1_reg_874 == 1'd1) & (exitcond3_reg_882 == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign col_1_fu_432_p2 = (ap_phi_mux_col_phi_fu_362_p4 + 11'd1);

assign exitcond2_fu_369_p2 = ((row_reg_347 == 10'd723) ? 1'b1 : 1'b0);

assign exitcond3_fu_426_p2 = ((ap_phi_mux_col_phi_fu_362_p4 == 11'd1280) ? 1'b1 : 1'b0);

assign line_buffer_0_0_va_address1 = tmp_12_reg_924_pp0_iter1_reg;

assign line_buffer_4_0_va_6_gep_fu_304_p3 = tmp_12_reg_924;

assign output_mat_data_V_din = tmp_8_i_reg_919;

assign p_Result_2_fu_652_p3 = y_mag_2_2_2_i_fu_574_p2[32'd7];

always @ (*) begin
    p_Result_3_fu_598_p4 = xs_V_1_i_i_i_cast_fu_594_p1;
    p_Result_3_fu_598_p4[32'd31] = |(1'd0);
end

always @ (*) begin
    p_Result_4_fu_642_p4 = xs_V_1_i_i1_i_cast_fu_638_p1;
    p_Result_4_fu_642_p4[32'd31] = |(1'd0);
end

assign p_Result_s_fu_608_p3 = x_mag_2_2_2_i_fu_544_p2[32'd7];

assign p_Val2_1_fu_580_p1 = x_mag_2_2_2_i_fu_544_p2;

assign p_Val2_3_fu_624_p1 = y_mag_2_2_2_i_fu_574_p2;

assign row_1_fu_375_p2 = (row_reg_347 + 10'd1);

assign start_out = real_start;

assign tmp1_fu_556_p2 = (tmp_fu_550_p2 + IN_WINDOW_val_val_1_2_fu_106);

assign tmp2_fu_562_p2 = (IN_WINDOW_val_val_0_2_fu_90 + tmp_19_fu_514_p2);

assign tmp3_fu_568_p2 = (tmp2_fu_562_p2 + tmp_13_fu_478_p2);

assign tmp6_fu_526_p2 = (tmp7_fu_520_p2 + IN_WINDOW_val_val_1_3_fu_102);

assign tmp7_fu_520_p2 = (IN_WINDOW_val_val_1_2_fu_106 + tmp_15_fu_490_p2);

assign tmp8_fu_538_p2 = (tmp9_fu_532_p2 + tmp_13_fu_478_p2);

assign tmp9_fu_532_p2 = (tmp_14_fu_484_p2 + tmp_17_fu_502_p2);

assign tmp_10_fu_471_p1 = tmp_9_fu_465_p2;

assign tmp_11_fu_725_p2 = (ap_phi_mux_col_phi_fu_362_p4 + 11'd2);

assign tmp_12_fu_731_p1 = tmp_11_fu_725_p2;

assign tmp_13_fu_478_p2 = IN_WINDOW_val_val_0_3_fu_86 << 8'd1;

assign tmp_14_fu_484_p2 = IN_WINDOW_val_val_0_2_fu_90 << 8'd1;

assign tmp_15_fu_490_p2 = IN_WINDOW_val_val_0_1_fu_94 << 8'd2;

assign tmp_16_fu_496_p2 = IN_WINDOW_val_val_1_3_fu_102 << 8'd1;

assign tmp_17_fu_502_p2 = IN_WINDOW_val_val_1_1_fu_110 << 8'd1;

assign tmp_18_fu_508_p2 = IN_WINDOW_val_val_2_3_fu_118 << 8'd2;

assign tmp_19_fu_514_p2 = IN_WINDOW_val_val_2_2_fu_122 << 8'd1;

assign tmp_1_fu_387_p2 = ((row_reg_347 > 10'd2) ? 1'b1 : 1'b0);

assign tmp_4_fu_393_p2 = ((row_reg_347 == 10'd0) ? 1'b1 : 1'b0);

assign tmp_5_fu_438_p2 = ((ap_phi_mux_col_phi_fu_362_p4 == 11'd0) ? 1'b1 : 1'b0);

assign tmp_5_i_cast_fu_628_p1 = y_mag_2_2_2_i_fu_574_p2;

assign tmp_6_fu_444_p2 = ((ap_phi_mux_col_phi_fu_362_p4 == 11'd1279) ? 1'b1 : 1'b0);

assign tmp_7_fu_450_p2 = (ap_phi_mux_col_phi_fu_362_p4 + 11'd2);

assign tmp_7_i_fu_668_p2 = (agg_result_V_i_i_i_fu_616_p3 + agg_result_V_i_i4_i_fu_660_p3);

assign tmp_8_fu_738_p1 = tmp_7_reg_899;

assign tmp_8_i_fu_674_p2 = (($signed(tmp_7_i_fu_668_p2) > $signed(32'd200)) ? 1'b1 : 1'b0);

assign tmp_9_fu_465_p2 = (11'd2 + ap_phi_mux_col_phi_fu_362_p4);

assign tmp_fu_550_p2 = (tmp_18_fu_508_p2 + tmp_16_fu_496_p2);

assign tmp_i_cast_fu_584_p1 = x_mag_2_2_2_i_fu_544_p2;

assign tmp_s_fu_381_p2 = ((row_reg_347 < 10'd720) ? 1'b1 : 1'b0);

assign x_mag_2_2_2_i_fu_544_p2 = (tmp8_fu_538_p2 + tmp6_fu_526_p2);

assign xs_V_1_i_i1_i_cast_fu_638_p1 = $signed(xs_V_4_fu_632_p2);

assign xs_V_1_i_i_i_cast_fu_594_p1 = $signed(xs_V_3_fu_588_p2);

assign xs_V_3_fu_588_p2 = ($signed(9'd0) - $signed(tmp_i_cast_fu_584_p1));

assign xs_V_4_fu_632_p2 = ($signed(9'd0) - $signed(tmp_5_i_cast_fu_628_p1));

assign y_mag_2_2_2_i_fu_574_p2 = (tmp3_fu_568_p2 + tmp1_fu_556_p2);

always @ (posedge ap_clk) begin
    tmp_12_reg_924[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    tmp_12_reg_924_pp0_iter1_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    IN_WINDOW_val_val_0_3_fu_86[7] <= 1'b0;
    IN_WINDOW_val_val_0_2_fu_90[7] <= 1'b0;
    IN_WINDOW_val_val_0_1_fu_94[7] <= 1'b0;
    IN_WINDOW_val_0_val_fu_98[7] <= 1'b0;
    IN_WINDOW_val_val_1_3_fu_102[7] <= 1'b0;
    IN_WINDOW_val_val_1_2_fu_106[7] <= 1'b0;
    IN_WINDOW_val_val_1_1_fu_110[7] <= 1'b0;
    IN_WINDOW_val_1_val_fu_114[7] <= 1'b0;
    IN_WINDOW_val_val_2_3_fu_118[7] <= 1'b0;
    IN_WINDOW_val_val_2_2_fu_122[7] <= 1'b0;
    IN_WINDOW_val_2_val_fu_126[7] <= 1'b0;
    IN_WINDOW_val_2_val_1_fu_130[7] <= 1'b0;
end

endmodule //hls_2DFilter
