// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "hls_2DFilter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic hls_2DFilter::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic hls_2DFilter::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> hls_2DFilter::ap_ST_fsm_state1 = "1";
const sc_lv<4> hls_2DFilter::ap_ST_fsm_state2 = "10";
const sc_lv<4> hls_2DFilter::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> hls_2DFilter::ap_ST_fsm_state8 = "1000";
const bool hls_2DFilter::ap_const_boolean_1 = true;
const sc_lv<32> hls_2DFilter::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> hls_2DFilter::ap_const_lv32_2 = "10";
const bool hls_2DFilter::ap_const_boolean_0 = false;
const sc_lv<1> hls_2DFilter::ap_const_lv1_0 = "0";
const sc_lv<32> hls_2DFilter::ap_const_lv32_1 = "1";
const sc_lv<1> hls_2DFilter::ap_const_lv1_1 = "1";
const sc_lv<32> hls_2DFilter::ap_const_lv32_3 = "11";
const sc_lv<10> hls_2DFilter::ap_const_lv10_0 = "0000000000";
const sc_lv<11> hls_2DFilter::ap_const_lv11_0 = "00000000000";
const sc_lv<10> hls_2DFilter::ap_const_lv10_2D0 = "1011010000";
const sc_lv<10> hls_2DFilter::ap_const_lv10_1 = "1";
const sc_lv<11> hls_2DFilter::ap_const_lv11_500 = "10100000000";
const sc_lv<11> hls_2DFilter::ap_const_lv11_1 = "1";
const sc_lv<8> hls_2DFilter::ap_const_lv8_1 = "1";
const sc_lv<8> hls_2DFilter::ap_const_lv8_0 = "00000000";
const sc_lv<9> hls_2DFilter::ap_const_lv9_0 = "000000000";
const sc_lv<10> hls_2DFilter::ap_const_lv10_7D = "1111101";
const sc_lv<8> hls_2DFilter::ap_const_lv8_FF = "11111111";

hls_2DFilter::hls_2DFilter(sc_module_name name) : sc_module(name), mVcdFile(0) {
    line_buffer_0_0_va_U = new hls_2DFilter_lineeOg("line_buffer_0_0_va_U");
    line_buffer_0_0_va_U->clk(ap_clk);
    line_buffer_0_0_va_U->reset(ap_rst);
    line_buffer_0_0_va_U->address0(line_buffer_0_0_va_address0);
    line_buffer_0_0_va_U->ce0(line_buffer_0_0_va_ce0);
    line_buffer_0_0_va_U->q0(line_buffer_0_0_va_q0);
    line_buffer_0_0_va_U->address1(line_buffer_0_0_va_1_reg_490);
    line_buffer_0_0_va_U->ce1(line_buffer_0_0_va_ce1);
    line_buffer_0_0_va_U->we1(line_buffer_0_0_va_we1);
    line_buffer_0_0_va_U->d1(line_buffer_1_0_va_q0);
    line_buffer_1_0_va_U = new hls_2DFilter_lineeOg("line_buffer_1_0_va_U");
    line_buffer_1_0_va_U->clk(ap_clk);
    line_buffer_1_0_va_U->reset(ap_rst);
    line_buffer_1_0_va_U->address0(line_buffer_1_0_va_address0);
    line_buffer_1_0_va_U->ce0(line_buffer_1_0_va_ce0);
    line_buffer_1_0_va_U->q0(line_buffer_1_0_va_q0);
    line_buffer_1_0_va_U->address1(line_buffer_1_0_va_1_reg_496);
    line_buffer_1_0_va_U->ce1(line_buffer_1_0_va_ce1);
    line_buffer_1_0_va_U->we1(line_buffer_1_0_va_we1);
    line_buffer_1_0_va_U->d1(input_mat_data_strea_dout);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_abs_i3_i_cast_fu_397_p1);
    sensitive << ( abs_i3_i_fu_389_p3 );

    SC_METHOD(thread_abs_i3_i_fu_389_p3);
    sensitive << ( tmp_2_i_cast_fu_375_p1 );
    sensitive << ( abscond_i2_i_fu_384_p2 );
    sensitive << ( neg_i1_i_fu_378_p2 );

    SC_METHOD(thread_abs_i_i_cast_fu_371_p1);
    sensitive << ( abs_i_i_fu_363_p3 );

    SC_METHOD(thread_abs_i_i_fu_363_p3);
    sensitive << ( tmp_i_cast_fu_349_p1 );
    sensitive << ( abscond_i_i_fu_358_p2 );
    sensitive << ( neg_i_i_fu_352_p2 );

    SC_METHOD(thread_abscond_i2_i_fu_384_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( exitcond1_reg_481_pp0_iter2_reg );
    sensitive << ( y_mag_2_2_2_i_reg_539 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_abscond_i_i_fu_358_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( exitcond1_reg_481_pp0_iter2_reg );
    sensitive << ( x_mag_2_2_2_i_reg_533 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( input_mat_data_strea_empty_n );
    sensitive << ( output_mat_data_stre_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond1_reg_481 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond1_reg_481_pp0_iter3_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( input_mat_data_strea_empty_n );
    sensitive << ( output_mat_data_stre_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond1_reg_481 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond1_reg_481_pp0_iter3_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( input_mat_data_strea_empty_n );
    sensitive << ( output_mat_data_stre_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond1_reg_481 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond1_reg_481_pp0_iter3_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( input_mat_data_strea_empty_n );
    sensitive << ( exitcond1_reg_481 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter4);
    sensitive << ( output_mat_data_stre_full_n );
    sensitive << ( exitcond1_reg_481_pp0_iter3_reg );

    SC_METHOD(thread_ap_condition_pp0_exit_iter1_state4);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond2_fu_175_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_col_1_fu_199_p2);
    sensitive << ( col_reg_164 );

    SC_METHOD(thread_exitcond1_fu_193_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( col_reg_164 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond2_fu_175_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( row_reg_153 );

    SC_METHOD(thread_input_mat_data_strea_blk_n);
    sensitive << ( input_mat_data_strea_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond1_reg_481 );

    SC_METHOD(thread_input_mat_data_strea_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond1_reg_481 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( exitcond2_fu_175_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_line_buffer_0_0_va_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_7_fu_205_p1 );

    SC_METHOD(thread_line_buffer_0_0_va_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_line_buffer_0_0_va_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_line_buffer_0_0_va_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond1_reg_481 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_line_buffer_1_0_va_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_7_fu_205_p1 );

    SC_METHOD(thread_line_buffer_1_0_va_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_line_buffer_1_0_va_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_line_buffer_1_0_va_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond1_reg_481 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_neg_i1_i_fu_378_p2);
    sensitive << ( tmp_2_i_cast_fu_375_p1 );

    SC_METHOD(thread_neg_i_i_fu_352_p2);
    sensitive << ( tmp_i_cast_fu_349_p1 );

    SC_METHOD(thread_output_mat_data_stre_blk_n);
    sensitive << ( output_mat_data_stre_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond1_reg_481_pp0_iter3_reg );

    SC_METHOD(thread_output_mat_data_stre_din);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond1_reg_481_pp0_iter3_reg );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( tmp_2_fu_417_p2 );

    SC_METHOD(thread_output_mat_data_stre_write);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond1_reg_481_pp0_iter3_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_row_1_fu_181_p2);
    sensitive << ( row_reg_153 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp2_fu_256_p2);
    sensitive << ( input_mat_data_strea_dout );
    sensitive << ( y_mag_2_0_2_i_fu_250_p2 );

    SC_METHOD(thread_tmp3_fu_325_p2);
    sensitive << ( IN_WINDOW_val_val_2_s_fu_94 );
    sensitive << ( tmp_10_fu_314_p2 );

    SC_METHOD(thread_tmp4_fu_413_p2);
    sensitive << ( tmp_8_reg_502_pp0_iter3_reg );
    sensitive << ( tmp_5_i_reg_545 );

    SC_METHOD(thread_tmp_10_fu_314_p2);
    sensitive << ( IN_WINDOW_val_val_2_1_fu_82 );

    SC_METHOD(thread_tmp_12_0_1_i_fu_232_p2);
    sensitive << ( tmp_fu_226_p2 );

    SC_METHOD(thread_tmp_1_fu_286_p2);
    sensitive << ( IN_WINDOW_val_val_1_1_fu_86 );

    SC_METHOD(thread_tmp_2_fu_417_p2);
    sensitive << ( tmp_4_reg_476 );
    sensitive << ( tmp4_fu_413_p2 );

    SC_METHOD(thread_tmp_2_i_cast_fu_375_p1);
    sensitive << ( y_mag_2_2_2_i_reg_539 );

    SC_METHOD(thread_tmp_3_fu_297_p2);
    sensitive << ( IN_WINDOW_val_1_val_2_reg_518 );

    SC_METHOD(thread_tmp_4_fu_187_p2);
    sensitive << ( exitcond2_fu_175_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( row_reg_153 );

    SC_METHOD(thread_tmp_4_i_fu_401_p2);
    sensitive << ( abs_i_i_cast_fu_371_p1 );
    sensitive << ( abs_i3_i_cast_fu_397_p1 );

    SC_METHOD(thread_tmp_5_i_fu_407_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( exitcond1_reg_481_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( tmp_4_i_fu_401_p2 );

    SC_METHOD(thread_tmp_7_fu_205_p1);
    sensitive << ( col_reg_164 );

    SC_METHOD(thread_tmp_8_fu_211_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( col_reg_164 );
    sensitive << ( exitcond1_fu_193_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_fu_226_p2);
    sensitive << ( IN_WINDOW_val_val_0_s_fu_78 );

    SC_METHOD(thread_tmp_i_cast_fu_349_p1);
    sensitive << ( x_mag_2_2_2_i_reg_533 );

    SC_METHOD(thread_x_mag_2_0_2_i_fu_244_p2);
    sensitive << ( line_buffer_0_0_va_q0 );
    sensitive << ( IN_WINDOW_val_val_0_1_fu_74 );

    SC_METHOD(thread_x_mag_2_1_1_i_fu_292_p2);
    sensitive << ( x_mag_2_0_2_i_reg_523 );
    sensitive << ( tmp_1_fu_286_p2 );

    SC_METHOD(thread_x_mag_2_1_2_i_fu_302_p2);
    sensitive << ( tmp_3_fu_297_p2 );
    sensitive << ( x_mag_2_1_1_i_fu_292_p2 );

    SC_METHOD(thread_x_mag_2_2_2_i_fu_320_p2);
    sensitive << ( tmp_12_reg_512 );
    sensitive << ( x_mag_2_2_i_fu_308_p2 );

    SC_METHOD(thread_x_mag_2_2_i_fu_308_p2);
    sensitive << ( IN_WINDOW_val_val_2_s_fu_94 );
    sensitive << ( x_mag_2_1_2_i_fu_302_p2 );

    SC_METHOD(thread_y_mag_2_0_1_i_fu_238_p2);
    sensitive << ( IN_WINDOW_val_val_0_1_fu_74 );
    sensitive << ( tmp_12_0_1_i_fu_232_p2 );

    SC_METHOD(thread_y_mag_2_0_2_i_fu_250_p2);
    sensitive << ( line_buffer_0_0_va_q0 );
    sensitive << ( y_mag_2_0_1_i_fu_238_p2 );

    SC_METHOD(thread_y_mag_2_2_2_i_fu_331_p2);
    sensitive << ( tmp2_reg_528 );
    sensitive << ( tmp3_fu_325_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond2_fu_175_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "hls_2DFilter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, input_mat_data_strea_dout, "(port)input_mat_data_strea_dout");
    sc_trace(mVcdFile, input_mat_data_strea_empty_n, "(port)input_mat_data_strea_empty_n");
    sc_trace(mVcdFile, input_mat_data_strea_read, "(port)input_mat_data_strea_read");
    sc_trace(mVcdFile, output_mat_data_stre_din, "(port)output_mat_data_stre_din");
    sc_trace(mVcdFile, output_mat_data_stre_full_n, "(port)output_mat_data_stre_full_n");
    sc_trace(mVcdFile, output_mat_data_stre_write, "(port)output_mat_data_stre_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, input_mat_data_strea_blk_n, "input_mat_data_strea_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond1_reg_481, "exitcond1_reg_481");
    sc_trace(mVcdFile, output_mat_data_stre_blk_n, "output_mat_data_stre_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, exitcond1_reg_481_pp0_iter3_reg, "exitcond1_reg_481_pp0_iter3_reg");
    sc_trace(mVcdFile, col_reg_164, "col_reg_164");
    sc_trace(mVcdFile, exitcond2_fu_175_p2, "exitcond2_fu_175_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, row_1_fu_181_p2, "row_1_fu_181_p2");
    sc_trace(mVcdFile, row_1_reg_471, "row_1_reg_471");
    sc_trace(mVcdFile, tmp_4_fu_187_p2, "tmp_4_fu_187_p2");
    sc_trace(mVcdFile, tmp_4_reg_476, "tmp_4_reg_476");
    sc_trace(mVcdFile, exitcond1_fu_193_p2, "exitcond1_fu_193_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter3, "ap_block_state6_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter4, "ap_block_state7_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond1_reg_481_pp0_iter1_reg, "exitcond1_reg_481_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond1_reg_481_pp0_iter2_reg, "exitcond1_reg_481_pp0_iter2_reg");
    sc_trace(mVcdFile, col_1_fu_199_p2, "col_1_fu_199_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, line_buffer_0_0_va_1_reg_490, "line_buffer_0_0_va_1_reg_490");
    sc_trace(mVcdFile, line_buffer_1_0_va_1_reg_496, "line_buffer_1_0_va_1_reg_496");
    sc_trace(mVcdFile, tmp_8_fu_211_p2, "tmp_8_fu_211_p2");
    sc_trace(mVcdFile, tmp_8_reg_502, "tmp_8_reg_502");
    sc_trace(mVcdFile, tmp_8_reg_502_pp0_iter1_reg, "tmp_8_reg_502_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_8_reg_502_pp0_iter2_reg, "tmp_8_reg_502_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_8_reg_502_pp0_iter3_reg, "tmp_8_reg_502_pp0_iter3_reg");
    sc_trace(mVcdFile, IN_WINDOW_val_1_val_1_reg_507, "IN_WINDOW_val_1_val_1_reg_507");
    sc_trace(mVcdFile, tmp_12_reg_512, "tmp_12_reg_512");
    sc_trace(mVcdFile, line_buffer_1_0_va_q0, "line_buffer_1_0_va_q0");
    sc_trace(mVcdFile, IN_WINDOW_val_1_val_2_reg_518, "IN_WINDOW_val_1_val_2_reg_518");
    sc_trace(mVcdFile, x_mag_2_0_2_i_fu_244_p2, "x_mag_2_0_2_i_fu_244_p2");
    sc_trace(mVcdFile, x_mag_2_0_2_i_reg_523, "x_mag_2_0_2_i_reg_523");
    sc_trace(mVcdFile, tmp2_fu_256_p2, "tmp2_fu_256_p2");
    sc_trace(mVcdFile, tmp2_reg_528, "tmp2_reg_528");
    sc_trace(mVcdFile, x_mag_2_2_2_i_fu_320_p2, "x_mag_2_2_2_i_fu_320_p2");
    sc_trace(mVcdFile, x_mag_2_2_2_i_reg_533, "x_mag_2_2_2_i_reg_533");
    sc_trace(mVcdFile, y_mag_2_2_2_i_fu_331_p2, "y_mag_2_2_2_i_fu_331_p2");
    sc_trace(mVcdFile, y_mag_2_2_2_i_reg_539, "y_mag_2_2_2_i_reg_539");
    sc_trace(mVcdFile, tmp_5_i_fu_407_p2, "tmp_5_i_fu_407_p2");
    sc_trace(mVcdFile, tmp_5_i_reg_545, "tmp_5_i_reg_545");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter1_state4, "ap_condition_pp0_exit_iter1_state4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, line_buffer_0_0_va_address0, "line_buffer_0_0_va_address0");
    sc_trace(mVcdFile, line_buffer_0_0_va_ce0, "line_buffer_0_0_va_ce0");
    sc_trace(mVcdFile, line_buffer_0_0_va_q0, "line_buffer_0_0_va_q0");
    sc_trace(mVcdFile, line_buffer_0_0_va_ce1, "line_buffer_0_0_va_ce1");
    sc_trace(mVcdFile, line_buffer_0_0_va_we1, "line_buffer_0_0_va_we1");
    sc_trace(mVcdFile, line_buffer_1_0_va_address0, "line_buffer_1_0_va_address0");
    sc_trace(mVcdFile, line_buffer_1_0_va_ce0, "line_buffer_1_0_va_ce0");
    sc_trace(mVcdFile, line_buffer_1_0_va_ce1, "line_buffer_1_0_va_ce1");
    sc_trace(mVcdFile, line_buffer_1_0_va_we1, "line_buffer_1_0_va_we1");
    sc_trace(mVcdFile, row_reg_153, "row_reg_153");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, tmp_7_fu_205_p1, "tmp_7_fu_205_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, IN_WINDOW_val_val_0_1_fu_74, "IN_WINDOW_val_val_0_1_fu_74");
    sc_trace(mVcdFile, IN_WINDOW_val_val_0_s_fu_78, "IN_WINDOW_val_val_0_s_fu_78");
    sc_trace(mVcdFile, IN_WINDOW_val_val_2_1_fu_82, "IN_WINDOW_val_val_2_1_fu_82");
    sc_trace(mVcdFile, IN_WINDOW_val_val_1_1_fu_86, "IN_WINDOW_val_val_1_1_fu_86");
    sc_trace(mVcdFile, IN_WINDOW_val_1_val_fu_90, "IN_WINDOW_val_1_val_fu_90");
    sc_trace(mVcdFile, IN_WINDOW_val_val_2_s_fu_94, "IN_WINDOW_val_val_2_s_fu_94");
    sc_trace(mVcdFile, tmp_fu_226_p2, "tmp_fu_226_p2");
    sc_trace(mVcdFile, tmp_12_0_1_i_fu_232_p2, "tmp_12_0_1_i_fu_232_p2");
    sc_trace(mVcdFile, y_mag_2_0_1_i_fu_238_p2, "y_mag_2_0_1_i_fu_238_p2");
    sc_trace(mVcdFile, y_mag_2_0_2_i_fu_250_p2, "y_mag_2_0_2_i_fu_250_p2");
    sc_trace(mVcdFile, tmp_1_fu_286_p2, "tmp_1_fu_286_p2");
    sc_trace(mVcdFile, tmp_3_fu_297_p2, "tmp_3_fu_297_p2");
    sc_trace(mVcdFile, x_mag_2_1_1_i_fu_292_p2, "x_mag_2_1_1_i_fu_292_p2");
    sc_trace(mVcdFile, x_mag_2_1_2_i_fu_302_p2, "x_mag_2_1_2_i_fu_302_p2");
    sc_trace(mVcdFile, x_mag_2_2_i_fu_308_p2, "x_mag_2_2_i_fu_308_p2");
    sc_trace(mVcdFile, tmp_10_fu_314_p2, "tmp_10_fu_314_p2");
    sc_trace(mVcdFile, tmp3_fu_325_p2, "tmp3_fu_325_p2");
    sc_trace(mVcdFile, tmp_i_cast_fu_349_p1, "tmp_i_cast_fu_349_p1");
    sc_trace(mVcdFile, abscond_i_i_fu_358_p2, "abscond_i_i_fu_358_p2");
    sc_trace(mVcdFile, neg_i_i_fu_352_p2, "neg_i_i_fu_352_p2");
    sc_trace(mVcdFile, abs_i_i_fu_363_p3, "abs_i_i_fu_363_p3");
    sc_trace(mVcdFile, tmp_2_i_cast_fu_375_p1, "tmp_2_i_cast_fu_375_p1");
    sc_trace(mVcdFile, abscond_i2_i_fu_384_p2, "abscond_i2_i_fu_384_p2");
    sc_trace(mVcdFile, neg_i1_i_fu_378_p2, "neg_i1_i_fu_378_p2");
    sc_trace(mVcdFile, abs_i3_i_fu_389_p3, "abs_i3_i_fu_389_p3");
    sc_trace(mVcdFile, abs_i_i_cast_fu_371_p1, "abs_i_i_cast_fu_371_p1");
    sc_trace(mVcdFile, abs_i3_i_cast_fu_397_p1, "abs_i3_i_cast_fu_397_p1");
    sc_trace(mVcdFile, tmp_4_i_fu_401_p2, "tmp_4_i_fu_401_p2");
    sc_trace(mVcdFile, tmp4_fu_413_p2, "tmp4_fu_413_p2");
    sc_trace(mVcdFile, tmp_2_fu_417_p2, "tmp_2_fu_417_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

hls_2DFilter::~hls_2DFilter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete line_buffer_0_0_va_U;
    delete line_buffer_1_0_va_U;
}

void hls_2DFilter::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(exitcond2_fu_175_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(exitcond1_fu_193_p2.read(), ap_const_lv1_1) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(exitcond2_fu_175_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter1_state4.read())) {
                ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter0.read();
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        } else if ((esl_seteq<1,1,1>(exitcond2_fu_175_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_enable_reg_pp0_iter4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_193_p2.read()))) {
        col_reg_164 = col_1_fu_199_p2.read();
    } else if ((esl_seteq<1,1,1>(exitcond2_fu_175_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        col_reg_164 = ap_const_lv11_0;
    }
    if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        row_reg_153 = ap_const_lv10_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        row_reg_153 = row_1_reg_471.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        IN_WINDOW_val_1_val_1_reg_507 = IN_WINDOW_val_1_val_fu_90.read();
        exitcond1_reg_481 = exitcond1_fu_193_p2.read();
        exitcond1_reg_481_pp0_iter1_reg = exitcond1_reg_481.read();
        tmp_8_reg_502_pp0_iter1_reg = tmp_8_reg_502.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && esl_seteq<1,1,1>(exitcond1_reg_481.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        IN_WINDOW_val_1_val_2_reg_518 = line_buffer_1_0_va_q0.read();
        IN_WINDOW_val_1_val_fu_90 = line_buffer_1_0_va_q0.read();
        IN_WINDOW_val_val_0_1_fu_74 = IN_WINDOW_val_val_0_s_fu_78.read();
        IN_WINDOW_val_val_0_s_fu_78 = line_buffer_0_0_va_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_481_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        IN_WINDOW_val_val_1_1_fu_86 = IN_WINDOW_val_1_val_1_reg_507.read();
        IN_WINDOW_val_val_2_1_fu_82 = tmp_12_reg_512.read();
        IN_WINDOW_val_val_2_s_fu_94 = IN_WINDOW_val_val_2_1_fu_82.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        exitcond1_reg_481_pp0_iter2_reg = exitcond1_reg_481_pp0_iter1_reg.read();
        exitcond1_reg_481_pp0_iter3_reg = exitcond1_reg_481_pp0_iter2_reg.read();
        tmp_8_reg_502_pp0_iter2_reg = tmp_8_reg_502_pp0_iter1_reg.read();
        tmp_8_reg_502_pp0_iter3_reg = tmp_8_reg_502_pp0_iter2_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_193_p2.read()))) {
        line_buffer_0_0_va_1_reg_490 =  (sc_lv<11>) (tmp_7_fu_205_p1.read());
        line_buffer_1_0_va_1_reg_496 =  (sc_lv<11>) (tmp_7_fu_205_p1.read());
        tmp_8_reg_502 = tmp_8_fu_211_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        row_1_reg_471 = row_1_fu_181_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(exitcond1_reg_481.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp2_reg_528 = tmp2_fu_256_p2.read();
        tmp_12_reg_512 = input_mat_data_strea_dout.read();
        x_mag_2_0_2_i_reg_523 = x_mag_2_0_2_i_fu_244_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond2_fu_175_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        tmp_4_reg_476 = tmp_4_fu_187_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_481_pp0_iter2_reg.read()))) {
        tmp_5_i_reg_545 = tmp_5_i_fu_407_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_481_pp0_iter1_reg.read()))) {
        x_mag_2_2_2_i_reg_533 = x_mag_2_2_2_i_fu_320_p2.read();
        y_mag_2_2_2_i_reg_539 = y_mag_2_2_2_i_fu_331_p2.read();
    }
}

void hls_2DFilter::thread_abs_i3_i_cast_fu_397_p1() {
    abs_i3_i_cast_fu_397_p1 = esl_sext<10,9>(abs_i3_i_fu_389_p3.read());
}

void hls_2DFilter::thread_abs_i3_i_fu_389_p3() {
    abs_i3_i_fu_389_p3 = (!abscond_i2_i_fu_384_p2.read()[0].is_01())? sc_lv<9>(): ((abscond_i2_i_fu_384_p2.read()[0].to_bool())? tmp_2_i_cast_fu_375_p1.read(): neg_i1_i_fu_378_p2.read());
}

void hls_2DFilter::thread_abs_i_i_cast_fu_371_p1() {
    abs_i_i_cast_fu_371_p1 = esl_sext<10,9>(abs_i_i_fu_363_p3.read());
}

void hls_2DFilter::thread_abs_i_i_fu_363_p3() {
    abs_i_i_fu_363_p3 = (!abscond_i_i_fu_358_p2.read()[0].is_01())? sc_lv<9>(): ((abscond_i_i_fu_358_p2.read()[0].to_bool())? tmp_i_cast_fu_349_p1.read(): neg_i_i_fu_352_p2.read());
}

void hls_2DFilter::thread_abscond_i2_i_fu_384_p2() {
    abscond_i2_i_fu_384_p2 = (!y_mag_2_2_2_i_reg_539.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): (sc_bigint<8>(y_mag_2_2_2_i_reg_539.read()) > sc_bigint<8>(ap_const_lv8_0));
}

void hls_2DFilter::thread_abscond_i_i_fu_358_p2() {
    abscond_i_i_fu_358_p2 = (!x_mag_2_2_2_i_reg_533.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): (sc_bigint<8>(x_mag_2_2_2_i_reg_533.read()) > sc_bigint<8>(ap_const_lv8_0));
}

void hls_2DFilter::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void hls_2DFilter::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void hls_2DFilter::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void hls_2DFilter::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[3];
}

void hls_2DFilter::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void hls_2DFilter::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(exitcond1_reg_481.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, input_mat_data_strea_empty_n.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_481_pp0_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, output_mat_data_stre_full_n.read())));
}

void hls_2DFilter::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(exitcond1_reg_481.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, input_mat_data_strea_empty_n.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_481_pp0_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, output_mat_data_stre_full_n.read())));
}

void hls_2DFilter::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(exitcond1_reg_481.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, input_mat_data_strea_empty_n.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_481_pp0_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, output_mat_data_stre_full_n.read())));
}

void hls_2DFilter::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void hls_2DFilter::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void hls_2DFilter::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(exitcond1_reg_481.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, input_mat_data_strea_empty_n.read()));
}

void hls_2DFilter::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void hls_2DFilter::thread_ap_block_state6_pp0_stage0_iter3() {
    ap_block_state6_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void hls_2DFilter::thread_ap_block_state7_pp0_stage0_iter4() {
    ap_block_state7_pp0_stage0_iter4 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_481_pp0_iter3_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, output_mat_data_stre_full_n.read()));
}

void hls_2DFilter::thread_ap_condition_pp0_exit_iter1_state4() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0))) {
        ap_condition_pp0_exit_iter1_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter1_state4 = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_ap_done() {
    if ((esl_seteq<1,1,1>(exitcond2_fu_175_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void hls_2DFilter::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void hls_2DFilter::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void hls_2DFilter::thread_col_1_fu_199_p2() {
    col_1_fu_199_p2 = (!col_reg_164.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(col_reg_164.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void hls_2DFilter::thread_exitcond1_fu_193_p2() {
    exitcond1_fu_193_p2 = (!col_reg_164.read().is_01() || !ap_const_lv11_500.is_01())? sc_lv<1>(): sc_lv<1>(col_reg_164.read() == ap_const_lv11_500);
}

void hls_2DFilter::thread_exitcond2_fu_175_p2() {
    exitcond2_fu_175_p2 = (!row_reg_153.read().is_01() || !ap_const_lv10_2D0.is_01())? sc_lv<1>(): sc_lv<1>(row_reg_153.read() == ap_const_lv10_2D0);
}

void hls_2DFilter::thread_input_mat_data_strea_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond1_reg_481.read(), ap_const_lv1_0))) {
        input_mat_data_strea_blk_n = input_mat_data_strea_empty_n.read();
    } else {
        input_mat_data_strea_blk_n = ap_const_logic_1;
    }
}

void hls_2DFilter::thread_input_mat_data_strea_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(exitcond1_reg_481.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        input_mat_data_strea_read = ap_const_logic_1;
    } else {
        input_mat_data_strea_read = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond2_fu_175_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_line_buffer_0_0_va_address0() {
    line_buffer_0_0_va_address0 =  (sc_lv<11>) (tmp_7_fu_205_p1.read());
}

void hls_2DFilter::thread_line_buffer_0_0_va_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        line_buffer_0_0_va_ce0 = ap_const_logic_1;
    } else {
        line_buffer_0_0_va_ce0 = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_line_buffer_0_0_va_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        line_buffer_0_0_va_ce1 = ap_const_logic_1;
    } else {
        line_buffer_0_0_va_ce1 = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_line_buffer_0_0_va_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(exitcond1_reg_481.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        line_buffer_0_0_va_we1 = ap_const_logic_1;
    } else {
        line_buffer_0_0_va_we1 = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_line_buffer_1_0_va_address0() {
    line_buffer_1_0_va_address0 =  (sc_lv<11>) (tmp_7_fu_205_p1.read());
}

void hls_2DFilter::thread_line_buffer_1_0_va_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        line_buffer_1_0_va_ce0 = ap_const_logic_1;
    } else {
        line_buffer_1_0_va_ce0 = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_line_buffer_1_0_va_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        line_buffer_1_0_va_ce1 = ap_const_logic_1;
    } else {
        line_buffer_1_0_va_ce1 = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_line_buffer_1_0_va_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(exitcond1_reg_481.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        line_buffer_1_0_va_we1 = ap_const_logic_1;
    } else {
        line_buffer_1_0_va_we1 = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_neg_i1_i_fu_378_p2() {
    neg_i1_i_fu_378_p2 = (!ap_const_lv9_0.is_01() || !tmp_2_i_cast_fu_375_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_bigint<9>(tmp_2_i_cast_fu_375_p1.read()));
}

void hls_2DFilter::thread_neg_i_i_fu_352_p2() {
    neg_i_i_fu_352_p2 = (!ap_const_lv9_0.is_01() || !tmp_i_cast_fu_349_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_bigint<9>(tmp_i_cast_fu_349_p1.read()));
}

void hls_2DFilter::thread_output_mat_data_stre_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_481_pp0_iter3_reg.read()))) {
        output_mat_data_stre_blk_n = output_mat_data_stre_full_n.read();
    } else {
        output_mat_data_stre_blk_n = ap_const_logic_1;
    }
}

void hls_2DFilter::thread_output_mat_data_stre_din() {
    output_mat_data_stre_din = (!tmp_2_fu_417_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_2_fu_417_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void hls_2DFilter::thread_output_mat_data_stre_write() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_481_pp0_iter3_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        output_mat_data_stre_write = ap_const_logic_1;
    } else {
        output_mat_data_stre_write = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void hls_2DFilter::thread_row_1_fu_181_p2() {
    row_1_fu_181_p2 = (!row_reg_153.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(row_reg_153.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void hls_2DFilter::thread_start_out() {
    start_out = real_start.read();
}

void hls_2DFilter::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void hls_2DFilter::thread_tmp2_fu_256_p2() {
    tmp2_fu_256_p2 = (!y_mag_2_0_2_i_fu_250_p2.read().is_01() || !input_mat_data_strea_dout.read().is_01())? sc_lv<8>(): (sc_biguint<8>(y_mag_2_0_2_i_fu_250_p2.read()) + sc_biguint<8>(input_mat_data_strea_dout.read()));
}

void hls_2DFilter::thread_tmp3_fu_325_p2() {
    tmp3_fu_325_p2 = (!IN_WINDOW_val_val_2_s_fu_94.read().is_01() || !tmp_10_fu_314_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(IN_WINDOW_val_val_2_s_fu_94.read()) + sc_biguint<8>(tmp_10_fu_314_p2.read()));
}

void hls_2DFilter::thread_tmp4_fu_413_p2() {
    tmp4_fu_413_p2 = (tmp_8_reg_502_pp0_iter3_reg.read() & tmp_5_i_reg_545.read());
}

void hls_2DFilter::thread_tmp_10_fu_314_p2() {
    tmp_10_fu_314_p2 = (!ap_const_lv8_1.is_01())? sc_lv<8>(): IN_WINDOW_val_val_2_1_fu_82.read() << (unsigned short)ap_const_lv8_1.to_uint();
}

void hls_2DFilter::thread_tmp_12_0_1_i_fu_232_p2() {
    tmp_12_0_1_i_fu_232_p2 = (!ap_const_lv8_0.is_01() || !tmp_fu_226_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_0) - sc_biguint<8>(tmp_fu_226_p2.read()));
}

void hls_2DFilter::thread_tmp_1_fu_286_p2() {
    tmp_1_fu_286_p2 = (!ap_const_lv8_1.is_01())? sc_lv<8>(): IN_WINDOW_val_val_1_1_fu_86.read() << (unsigned short)ap_const_lv8_1.to_uint();
}

void hls_2DFilter::thread_tmp_2_fu_417_p2() {
    tmp_2_fu_417_p2 = (tmp4_fu_413_p2.read() & tmp_4_reg_476.read());
}

void hls_2DFilter::thread_tmp_2_i_cast_fu_375_p1() {
    tmp_2_i_cast_fu_375_p1 = esl_sext<9,8>(y_mag_2_2_2_i_reg_539.read());
}

void hls_2DFilter::thread_tmp_3_fu_297_p2() {
    tmp_3_fu_297_p2 = (!ap_const_lv8_1.is_01())? sc_lv<8>(): IN_WINDOW_val_1_val_2_reg_518.read() << (unsigned short)ap_const_lv8_1.to_uint();
}

void hls_2DFilter::thread_tmp_4_fu_187_p2() {
    tmp_4_fu_187_p2 = (!row_reg_153.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(row_reg_153.read() != ap_const_lv10_0);
}

void hls_2DFilter::thread_tmp_4_i_fu_401_p2() {
    tmp_4_i_fu_401_p2 = (!abs_i_i_cast_fu_371_p1.read().is_01() || !abs_i3_i_cast_fu_397_p1.read().is_01())? sc_lv<10>(): (sc_bigint<10>(abs_i_i_cast_fu_371_p1.read()) + sc_bigint<10>(abs_i3_i_cast_fu_397_p1.read()));
}

void hls_2DFilter::thread_tmp_5_i_fu_407_p2() {
    tmp_5_i_fu_407_p2 = (!tmp_4_i_fu_401_p2.read().is_01() || !ap_const_lv10_7D.is_01())? sc_lv<1>(): (sc_bigint<10>(tmp_4_i_fu_401_p2.read()) > sc_bigint<10>(ap_const_lv10_7D));
}

void hls_2DFilter::thread_tmp_7_fu_205_p1() {
    tmp_7_fu_205_p1 = esl_zext<64,11>(col_reg_164.read());
}

void hls_2DFilter::thread_tmp_8_fu_211_p2() {
    tmp_8_fu_211_p2 = (!col_reg_164.read().is_01() || !ap_const_lv11_0.is_01())? sc_lv<1>(): sc_lv<1>(col_reg_164.read() != ap_const_lv11_0);
}

void hls_2DFilter::thread_tmp_fu_226_p2() {
    tmp_fu_226_p2 = (!ap_const_lv8_1.is_01())? sc_lv<8>(): IN_WINDOW_val_val_0_s_fu_78.read() << (unsigned short)ap_const_lv8_1.to_uint();
}

void hls_2DFilter::thread_tmp_i_cast_fu_349_p1() {
    tmp_i_cast_fu_349_p1 = esl_sext<9,8>(x_mag_2_2_2_i_reg_533.read());
}

void hls_2DFilter::thread_x_mag_2_0_2_i_fu_244_p2() {
    x_mag_2_0_2_i_fu_244_p2 = (!line_buffer_0_0_va_q0.read().is_01() || !IN_WINDOW_val_val_0_1_fu_74.read().is_01())? sc_lv<8>(): (sc_biguint<8>(line_buffer_0_0_va_q0.read()) - sc_biguint<8>(IN_WINDOW_val_val_0_1_fu_74.read()));
}

void hls_2DFilter::thread_x_mag_2_1_1_i_fu_292_p2() {
    x_mag_2_1_1_i_fu_292_p2 = (!x_mag_2_0_2_i_reg_523.read().is_01() || !tmp_1_fu_286_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(x_mag_2_0_2_i_reg_523.read()) - sc_biguint<8>(tmp_1_fu_286_p2.read()));
}

void hls_2DFilter::thread_x_mag_2_1_2_i_fu_302_p2() {
    x_mag_2_1_2_i_fu_302_p2 = (!tmp_3_fu_297_p2.read().is_01() || !x_mag_2_1_1_i_fu_292_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_3_fu_297_p2.read()) + sc_biguint<8>(x_mag_2_1_1_i_fu_292_p2.read()));
}

void hls_2DFilter::thread_x_mag_2_2_2_i_fu_320_p2() {
    x_mag_2_2_2_i_fu_320_p2 = (!x_mag_2_2_i_fu_308_p2.read().is_01() || !tmp_12_reg_512.read().is_01())? sc_lv<8>(): (sc_biguint<8>(x_mag_2_2_i_fu_308_p2.read()) + sc_biguint<8>(tmp_12_reg_512.read()));
}

void hls_2DFilter::thread_x_mag_2_2_i_fu_308_p2() {
    x_mag_2_2_i_fu_308_p2 = (!x_mag_2_1_2_i_fu_302_p2.read().is_01() || !IN_WINDOW_val_val_2_s_fu_94.read().is_01())? sc_lv<8>(): (sc_biguint<8>(x_mag_2_1_2_i_fu_302_p2.read()) - sc_biguint<8>(IN_WINDOW_val_val_2_s_fu_94.read()));
}

void hls_2DFilter::thread_y_mag_2_0_1_i_fu_238_p2() {
    y_mag_2_0_1_i_fu_238_p2 = (!tmp_12_0_1_i_fu_232_p2.read().is_01() || !IN_WINDOW_val_val_0_1_fu_74.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_12_0_1_i_fu_232_p2.read()) - sc_biguint<8>(IN_WINDOW_val_val_0_1_fu_74.read()));
}

void hls_2DFilter::thread_y_mag_2_0_2_i_fu_250_p2() {
    y_mag_2_0_2_i_fu_250_p2 = (!y_mag_2_0_1_i_fu_238_p2.read().is_01() || !line_buffer_0_0_va_q0.read().is_01())? sc_lv<8>(): (sc_biguint<8>(y_mag_2_0_1_i_fu_238_p2.read()) - sc_biguint<8>(line_buffer_0_0_va_q0.read()));
}

void hls_2DFilter::thread_y_mag_2_2_2_i_fu_331_p2() {
    y_mag_2_2_2_i_fu_331_p2 = (!tmp2_reg_528.read().is_01() || !tmp3_fu_325_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp2_reg_528.read()) + sc_biguint<8>(tmp3_fu_325_p2.read()));
}

void hls_2DFilter::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond2_fu_175_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

